### ISSUE TITLE
Add code coverage support

### ISSUE THREAD

**Issue by volks73** [Theia-Scientific/tspng#82]
The Codecov tool should be added to the CI workflow to help guide testing and development.

**Comment by volks73** [comment]
This was resolved with https://github.com/Theia-Scientific/tspng/commit/79d00bd865dedcafd508cb7b80ee3351d1fbe5e9, where I accidentally pushed to `main` instead of creating a PR.

**Comment by mikhail-vl** [comment]
@volks73 You need to add branch protection to avoid that.
